version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-prod
    ports:
      - "80:80"
    networks:
      - backend_laravel

networks:
  backend_laravel:
    external: true
